PERIODS = {"Achaemenid": "First Millennium",
            "Archaic": "Third Millennium",
            "Early Dynastic": "Third Millennium",
            "EarlyDynastic": "Third Millennium",
            "Ebla": "Third Millennium",
            "First Millennium": "First Millennium",
            "FirstMillennium": "First Millennium",
            "Hellenistic": "First Millennium",
            "Hittite": "Second Millennium",
            "Lagaš II": "Second Millennium",
            "LagašII": "Second Millennium",
            "Late Babylonian": "First Millennium",
            "LateBabylonian": "First Millennium",
            "Middle Assyrian": "Second Millennium",
            "Middle Babylonian": "Second Millennium",
            "Middle Hittite": "Second Millennium",
            "MiddleAssyrian": "Second Millennium",
            "MiddleBabylonian": "Second Millennium",
            "MiddleHittite": "First Millennium",
            "Neo-Assyrian": "First Millennium",
            "Neo-Babylonian": "First Millennium",
            "NeoAssyrian": "First Millennium",
            "NeoBabylonian": "First Millennium",
            "Old Akkadian": "Third Millennium",
            "Old Assyrian": "Second Millennium",
            "Old Babylonian": "Second Millennium",
            "OldAkkadian": "Second Millennium",
            "OldAssyrian": "Second Millennium",
            "OldBabylonian": "Second Millennium",
            "Parthian": "First Millennium",
            "Standard Babylonian": "First Millennium",
            "StandardBabylonian": "First Millennium",
            "Uncertain or unspecified": "_",
            "Uncertainorunspecified": "_",
            "Ur III": "Second Millennium",
            "UrIII": "Second Millennium",
            "Urartian": "First Millennium",
            "UrukIII": "Third Millennium",
            "UrukIV": "Third Millennium",
            "_": "_"}

WORDLANGS = {"Akkadian": "akkadian",
            "Aramaic": "aramean",
            "Canaanite": "canaanite",
            "Cuneiform": "cuneiform",
            "Early Akkadian": "old akkadian",
            "EarlyAkkadian": "old akkadian",
            "Eblaite": "eblaite",
            "Egyptian": "egyptian",
            "Elamite": "elamite",
            "Greek": "greek",
            "Hieroglyphic Luwian": "luwian",
            "Hittite": "hittite",
            "Hurrian": "hurrian",
            "Late Babylonian": "late babylonian",
            "LateBabylonian": "late babylonian",
            "Middle Assyrian": "middle assyrian",
            "Middle Babylonian": "middle assyrian",
            "Middle Babylonian peripheral": "middle babylonian",
            "MiddleAssyrian": "middle assyrian",
            "MiddleBabylonian": "middle babylonian",
            "MiddleBabylonianperipheral": "middle babylonian",
            "Neo-Assyrian": "neo-assyrian",
            "Neo-Babylonian": "neo-babylonian",
            "Old Akkadian": "old akkadian",
            "Old Assyrian": "old assyrian",
            "Old Babylonian": "old babylonian",
            "Old Persian": "old persian",
            "OldAkkadian": "old akkadian",
            "OldAssyrian": "old assyrian",
            "OldBabylonian": "old babylonian",
            "OldPersian": "old persian",
            "Proto-cuneiform": "proto-cuneiform",
            "Standard Babylonian": "standard babylonian",
            "StandardBabylonian": "standard babylonian",
            "Sumerian": "sumerian",
            "Sumerian Emesal": "sumerian emesal",
            "SumerianEmesal": "sumerian emesal",
            "Ugaritic": "ugaritic",
            "Urartian": "urartian",
            "akk-x-neobab-949": "neo-babylonian"}

TEXTLANGS = {"Akk": "akk",
            "Akkadian": "akkadian",
            "Akkadian, Aramaic": "akkadian|aramaic",
            "Akkadian, Aramaic, Luwian": "akkadian|aramaic|luwian",
            "Akkadian, Egyptian": "akkadian|egyptian",
            "Akkadian, Old Persian": "akkadian|old persian",
            "Akkadian, Old Persian, Elamite": "akkadian|old persian|elamite",
            "Akkadian, Old Persian, Elamite, Egyptian": "akkadian|old persian|elamite|egyptian",
            "Akkadian, Sumerian": "akkadian|sumerian",
            "Akkadian, Urartian": "akkadian|urartian",
            "Akkadian, with Aramaic epigraph": "akkadian|aramaic",
            "Akkadian; Aramaic": "akkadian|aramaic",
            "AkkadianAramaic": "akkadian|aramaic",
            "AkkadianAramaicLuwian": "akkadian|aramaic|luwian",
            "AkkadianEgyptian": "akkadian|egyptian",
            "AkkadianOldPersian": "akkadian|old persian",
            "AkkadianOldPersianElamite": "akkadian|old persian|elamite",
            "AkkadianOldPersianElamiteEgyptian": "akkadian|old persian|elamite|egyptian",
            "AkkadianUrartian": "akkadian|urartian",
            "Aramaic": "aramaic",
            "Assyrian": "assyrian",
            "Eblaite": "eblaite",
            "Elamite": "elamite",
            "Hittite": "hittite",
            "Hurrian": "hurrian",
            "Neo-Assyrian": "neo-assyrian",
            "Neo-Babylonian": "neo-babylonian",
            "Old Persian": "old persian",
            "Old Persian, Elamite": "old persian|elamite",
            "OldPersian": "oldpersian",
            "OldPersianElamite": "old persian|elamite",
            "Sumerian": "sumerian",
            "Sumerian, Akkadian": "sumerian|akkadian",
            "SumerianAkkadian": "sumerian|akkadian",
            "Ugaritic": "ugaritic",
            "Uncertain or unspecified": "_",
            "Uncertainorunspecified": "_",
            "Urartian": "urartian",
            "_": "_"}



LANG_TO_PERIOD = {"Aramaic": "First Millennium",
            "Early Akkadian": "Third Millennium",
            "EarlyAkkadian": "Third Millennium",
            "Eblaite": "Third Millennium",
            "Greek": "First Millennium",
            "Hieroglyphic Luwian": "First Millennium",
            "Hittite": "Second Millennium",
            "Hurrian": "Second Millennium",
            "Late Babylonian": "First Millennium",
            "LateBabylonian": "First Millennium",
            "Middle Assyrian": "Second Millennium",
            "Middle Babylonian": "Second Millennium",
            "Middle Babylonian peripheral": "Second Millennium",
            "MiddleAssyrian": "Second Millennium",
            "MiddleBabylonian": "Second Millennium",
            "MiddleBabylonianperipheral": "Second Millennium",
            "Neo-Assyrian": "First Millennium",
            "Neo-Babylonian": "First Millennium",
            "Old Akkadian": "Third Millennium",
            "Old Assyrian": "Third Millennium",
            "Old Babylonian": "Second Millennium",
            "Old Persian": "First Millennium",
            "OldAkkadian": "Third Millennium",
            "OldAssyrian": "Second Millennium",
            "OldBabylonian": "Second Millennium",
            "OldPersian": "First Millennium",
            "Proto-cuneiform": "Third Millennium",
            "Standard Babylonian": "First Millennium",
            "StandardBabylonian": "First Millennium",
            "Sumerian Emesal": "First Millennium",
            "SumerianEmesal": "First Millennium",
            "Ugaritic": "Second Millennium",
            "Urartian": "First Millennium",
            "akk-x-neobab-949": "First Millennium"}

POSMAP = {"Divine": "DN",
        "Ethnos": "EN",
        "Field": "FN",
        "Geographical": "GN",
        "Month": "MN",
        "NINDA": "N",
        "Object": "ON",
        "Personal": "PN",
        "Royal": "RN",
        "Settlement": "SN",
        "Temple" : "TN",
        "Vi": "V/i",
        "Vi&amp;&amp;Vi": "V/i&amp;&amp;V/i",
        "Vt": "V/t",
        "Vt&amp;&amp;Vt": "V/t&amp;&amp;V/t",
        "Watercourse": "WN",
        "adjective": "AJ",
        "adverb": "AV",
        "conjunction": "CNJ",
        "demonstrative": "DP",
        "determinative": "DET",
        "independentanaphoric": "IP",
        "interjection": "J",
        "interrogative": "IP",
        "noun": "N",
        "number": "n",
        "preposition": "PRP",
        "reflexivereciprocal": "RP",
        "relative": "REL",
        "unknown": "u",
        "verb": "V"}
